nelmio_api_doc:
  documentation:
    info:
      title: get.typo3.org
      description: REST API for getting information about TYPO3 releases
      version: 1.0.0
    components:
      securitySchemes:
        Basic:
          type: http
          scheme: basic
    security:
      - Basic: []
  areas:
    default:
      path_patterns:
        - ^/api/v1(?!/doc$)
