twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        baseUrl: '%env(BASE_URL)%'
        packagist:
            search: https://packagist.org/explore/?type=typo3-cms-extension
            submit: https://packagist.org/packages/submit
