magephp:
  log_dir: ./.mage/logs
  composer:
    path: composer
  exclude:
    - .ddev
    - .git
    - .github
    - .mage
    - .vscode
    - tests
    - var
    - .editorconfig
    - .env
    - .env.ddev
    - .env.dist
    - .env.test
    - .env.local
    - .gitattributes
    - .gitignore
    - .mage.yml
    - .php_cs.cache
    - .php_cs.dist
    - .phplint.cache
    - .phplint.yml
    - .phpunit.result.cache
    - composer.json
    - composer.lock
    - LICENSE
    - phpunit.xml.dist
    - README.md
    - symfony.lock
  environments:
    develop:
      user: get-dev
      from: ./
      host_path: ./site/mage/
      releases: 3
      hosts:
        - web01.typo3server.ch
      pre-deploy:
        - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local" }
        - exec: { cmd: "echo \"CORS_ALLOW_ORIGIN=^https?://get-dev\\.web01\\.typo3server\\.ch:?[0-9]*$\" >> .env.local" }
        - exec: { cmd: "echo \"BASE_URL=https://get-dev.web01.typo3server.ch\" >> .env.local" }
        - exec: { cmd: "cat .env.local" }
        - composer/install: { flags: '--no-dev --no-progress --optimize-autoloader' }
      on-deploy:
        - fs/link: { from: "../../../shared/var", to: "var" }
        - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
        - fs/copy: { from: 'cnf/nginx.conf', to: '../../../../cnf/nginx.conf' }
      on-release:
      post-release:
        - exec: { cmd: "nginx-reload" }
        - exec: { cmd: "php-reload" }
        - fs/remove: { file: "var/cache", flags: "-rf" }
        - exec: { cmd: "php ./bin/console doctrine:migrations:migrate --no-interaction" }
        - exec: { cmd: "php ./bin/console cache:warmup -vvv" }
      post-deploy:
