magephp:
    log_dir: ./.mage/logs
    composer:
        path: composer
    exclude:
        - ./.[!.e]*
        - ./public/p
        - ./public/p2
        - ./public/satis
        - ./public/aliases.json
        - ./public/packages.json
        - ./stubs
        - ./tests
        - ./tools
        - ./var
        - ./LICENSE
        - ./phpstan.neon
        - ./phpunit.xml.dist
        - ./README.md
        - ./rector.php
    environments:
        develop:
            user: get-dev
            from: ./* ./.env
            host_path: ./site/mage/
            releases: 3
            hosts:
                - get01.typo3server.ch
            pre-deploy:
                - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local", desc: "Create .env.local" }
                - composer/install: { flags: '--no-dev --no-progress --optimize-autoloader' }
            on-deploy:
                - exec: { cmd: 'mkdir -p var', desc: 'Create var folder' }
                - exec: { cmd: 'mkdir -p var/satis', desc: 'Create var/satis folder' }
                - exec: { cmd: 'test -d ~/site/shared/public/satis || mkdir -p ~/site/shared/public/satis', desc: 'Create shared/public/satis folder' }
                - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
                - fs/link: { from: "../../../../shared/public/satis", to: "public/satis" }
                - fs/link: { from: "satis/p", to: "public/p" }
                - fs/link: { from: "satis/p2", to: "public/p2" }
                - fs/link: { from: "satis/aliases.json", to: "public/aliases.json" }
                - fs/link: { from: "satis/packages.json", to: "public/packages.json" }
                - exec: { cmd: "sqlite3 ~/site/mage/current/var/gettr.db '.backup var/gettr.db'", desc: "Copy DB" }
                - exec: { cmd: "php-restart", desc: "Restart PHP and reset OPcache" }
                - exec: { cmd: "php ./bin/console doctrine:migrations:sync-metadata-storage --no-interaction", desc: "Synchronize DB Migrations" }
                - exec: { cmd: "php ./bin/console doctrine:migrations:migrate --no-interaction", desc: "Apply DB Migrations" }
                - exec: { cmd: "php ./bin/console cache:warmup --env=prod", desc: "Cache Warmup", timeout: 600 }
                - exec: { cmd: "crontab cnf/crontab-dev.cron", desc: "Install crontab" }
                - fs/copy: { from: 'cnf/nginx.conf', to: '../../../../cnf/nginx.conf' }
            on-release:
                - exec: { cmd: "nginx-reload", desc: "Reload Nginx Configuration" }
            post-release:
            post-deploy:
        production:
            user: get
            from: ./* ./.env
            host_path: ./site/mage/
            releases: 3
            hosts:
                - get01.typo3server.ch
            pre-deploy:
                - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local", desc: "Create .env.local" }
                - composer/install: { flags: '--no-dev --no-progress --optimize-autoloader' }
            on-deploy:
                - exec: { cmd: 'mkdir -p var', desc: 'Create var folder' }
                - exec: { cmd: 'mkdir -p var/satis', desc: 'Create var/satis folder' }
                - exec: { cmd: 'test -d ~/site/shared/public/satis || mkdir -p ~/site/shared/public/satis', desc: 'Create shared/public/satis folder' }
                - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
                - fs/link: { from: "../../../../shared/public/satis", to: "public/satis" }
                - fs/link: { from: "satis/p", to: "public/p" }
                - fs/link: { from: "satis/p2", to: "public/p2" }
                - fs/link: { from: "satis/aliases.json", to: "public/aliases.json" }
                - fs/link: { from: "satis/packages.json", to: "public/packages.json" }
                - exec: { cmd: "sqlite3 ~/site/mage/current/var/gettr.db '.backup var/gettr.db'", desc: "Copy DB" }
                - exec: { cmd: "php-restart", desc: "Restart PHP and reset OPcache" }
                - exec: { cmd: "php ./bin/console doctrine:migrations:sync-metadata-storage --no-interaction", desc: "Synchronize DB Migrations" }
                - exec: { cmd: "php ./bin/console doctrine:migrations:migrate --no-interaction", desc: "Apply DB Migrations" }
                - exec: { cmd: "php ./bin/console cache:warmup --env=prod", desc: "Cache Warmup", timeout: 600 }
                - exec: { cmd: "crontab cnf/crontab.cron", desc: "Install crontab" }
                - fs/copy: { from: 'cnf/nginx.conf', to: '../../../../cnf/nginx.conf' }
            on-release:
                - exec: { cmd: "nginx-reload", desc: "Reload Nginx Configuration" }
            post-release:
            post-deploy:
        stage:
            user: get-stage
            from: ./* ./.env
            host_path: ./site/mage/
            releases: 3
            hosts:
                - get.typo3.gilbertsoft.org
            pre-deploy:
                - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local", desc: "Create .env.local" }
                - composer/install: { flags: '--no-dev --no-progress --optimize-autoloader' }
            on-deploy:
                - exec: { cmd: 'test -d ~/site/shared || mkdir -p ~/site/shared', desc: 'Create shared folder' }
                - exec: { cmd: 'test -d ~/site/shared/public || mkdir -p ~/site/shared/public', desc: 'Create shared/public folder' }
                - exec: { cmd: 'test -d ~/site/shared/public/p || mkdir -p ~/site/shared/public/p', desc: 'Create shared/public/p folder' }
                - exec: { cmd: 'test -d ~/site/shared/public/p2 || mkdir -p ~/site/shared/public/p2', desc: 'Create shared/public/p2 folder' }
                - exec: { cmd: 'test -d ~/site/shared/satis || mkdir -p ~/site/shared/satis', desc: 'Create shared/satis folder' }
                - exec: { cmd: 'test -d ~/site/shared/satis/Web || mkdir -p ~/site/shared/satis/Web', desc: 'Create shared/satis/Web folder' }
                - exec: { cmd: 'test -d ~/site/shared/var || mkdir -p ~/site/shared/var', desc: 'Create shared/var folder' }
                - fs/link: { from: "../../../shared/var", to: "var" }
                - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
                - fs/link: { from: "../../../../shared/public/p", to: "public/p" }
                - fs/link: { from: "../../../../shared/public/p2", to: "public/p2" }
                - fs/link: { from: "../../../../shared/public/packages.json", to: "public/packages.json" }
                - fs/link: { from: "../../../../shared/public/satis.html", to: "public/satis.html" }
                - fs/copy: { from: 'cnf/nginx.conf', to: '../../../../cnf/nginx.conf' }
            on-release:
            post-release:
                - exec: { cmd: "nginx-reload", desc: "Reload Nginx Configuration" }
                - exec: { cmd: "php-restart", desc: "Restart PHP and reset OPcache" }
                - symfony/cache-clear: { env: "prod" }
                - exec: { cmd: "php ./bin/console doctrine:migrations:migrate --no-interaction", desc: "Apply DB Migrations" }
                - symfony/cache-warmup: { env: "prod" }
                - exec: { cmd: "crontab cnf/crontab-stage.cron", desc: "Install crontab" }
            post-deploy:
