magephp:
  log_dir: ./.mage/logs
  composer:
    path: composer
  exclude:
    - .ddev
    - .git
    - .github
    - .mage
    - .vscode
    - tests
    - var
    - .editorconfig
    - .env
    - .env.ddev
    - .env.dist
    - .env.test
    - .env.local
    - .gitattributes
    - .gitignore
    - .mage.yml
    - .php_cs.cache
    - .php_cs.dist
    - .phplint.cache
    - .phplint.yml
    - .phpunit.result.cache
    - composer.json
    - composer.lock
    - LICENSE
    - phpunit.xml.dist
    - README.md
    - symfony.lock
  environments:
    develop:
      user: get
      from: ./
      host_path: ./site/mage/
      releases: 3
      hosts:
        - web01.typo3server.ch
      pre-deploy:
        - exec: { cmd: "cp .env.test .env"}
        - exec: { cmd: "composer install --no-dev --no-progress --optimize-autoloader"}
      on-deploy:
        - fs/link: { from: "../../../shared/var", to: "var" }
        - fs/link: { from: "../../../shared/.env", to: ".env" }
        - exec: { cmd: "cp cnf/nginx.conf ../../../../cnf/nginx.conf"}
      on-release:
      post-release:
        - exec: { cmd: "nginx-reload"}
        - exec: { cmd: "php-reload"}
        - exec: { cmd: "rm -rf var/cache"}
        - exec: { cmd: "php ./bin/console doctrine:migrations:migrate --no-interaction"}
        - exec: { cmd: "php ./bin/console cache:warmup -vvv"}
      post-deploy:
