security:
    providers:
        users_in_memory:
            memory:
                users:
                    preview:
                        password: '%env(PASSWORD_STAGING_PREVIEW)%'
                        roles: ROLE_GUEST
