name: Continuous Deployment (CD)

on:
  workflow_run:
    workflows: [Continuous Integration (CI)]
    types: [completed]
    branches:
      - develop
      - production
      - stage

jobs:
  deployment:
    name: Deployment
    if: ${{ github.event.workflow_run.event == 'push' }} && ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deployment.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
