name: Integration (CI)

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set up PHP Version
      run: |
        sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
        php -v
    - name: Update Composer
      run: |
        sudo composer self-update
        composer --version
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ matrix.php }}-composer-
    - name: Install
      run: |
        composer install --no-progress
    - name: Lint
      if: always()
      run: |
        composer test:php:lint
    - name: CGL
      if: always()
      run: |
        composer test:php:cgl
    - name: Unit Tests
      if: always()
      run: |
        composer test:php:unit
    - name: Functional Tests
      run: |
        composer test:php:functional
    - name: Archive Logs
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: logs
        path: var/log

