name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version to be used for the deployment.'
        default: '8.2'
        required: true
        type: choice
        options:
          - '8.2'
          - 'latest'
          - 'nightly'
      composer_version:
        description: 'Composer version to be used for the deployment.'
        default: '2'
        required: true
        type: string

jobs:
  deployment:
    name: Deployment
    uses: ./.github/workflows/deployment.yml
    with:
      php_version: ${{ github.event.inputs.php_version }}
      composer_version: ${{ github.event.inputs.composer_version }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
